apiVersion: apps/v1
kind: Deployment
metadata:
  name: flm
spec:
  replicas: 7
  selector:
    matchLabels:
       app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: cont1
          image: shaikmustafa/paytm:bank
          ports:
            - containerPort: 80
